### PR TITLE
Fixes gameplay ui screen

### LINKED ISSUE #8: Change gameplay screen theme
Currently, the UI of the gameplay screen at `/play` is very boring. We want to have something better than than that. Contributor is free to implement their own ideas for the theme.

### PR DESCRIPTION
**Pull request by SudiptaPaul-31**
Resolves #8 

Fixes:

- Fixed gameplay screen UI
- Added dark mode and light mode 
- Responsive UI

## Updated design

https://github.com/user-attachments/assets/dc252494-d544-441a-bf55-560b98fafcb8

### CODE REVIEW

**Comment by SoarinSkySagar** [comment]
@SudiptaPaul-31 please fix this error. run `pnpm run build` to recreate this error

image

File: client/app/play/page.tsx [hunk 1]
```diff
@@ -31,88 +41,181 @@ const Square: React.FC<SquareProps> = ({ value, onClick, winningSquare }) => (
...
         return { winner: squares[a], line: [a, b, c] };
       }
     }
     return null;
   };
 
   const winner = calculateWinner(squares);
-  const isDraw = !winner && squares.every(square => square !== null);
-  
+  const isDraw = !winner && squares.every((square) => square !== null);
```
Comment (SoarinSkySagar) [inline client/app/play/page.tsx:78]: The error occurs here

**Review by SoarinSkySagar — CHANGES_REQUESTED** [review]

**Comment by SoarinSkySagar** [comment]
LGTM!

**Review by SoarinSkySagar — APPROVED** [review]
